matrix:
  include:
  
    - language: java
      jdk: oraclejdk8
      
      cache:
        directories:
          - $HOME/.m2
          
      before_script:
        - cd services
        
      script:
        - mvn install


    - language: node_js
      node_js:
        - "6"
        
      cache:
        directories:
          - node_modules

      sudo: required
      
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
            - google-chrome-beta

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      before_script:
        - cd web
        - npm install -g @angular/cli
        - npm install
        - npm run-script build

notifications:
  email:
    - durandben@gmail.com
