matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd services
      script:
        - mvn install

    - language: node_js
      node_js:
        - "6"
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd web
        - npm install -g @angular/cli

notifications:
  email:
    - durandben@gmail.com
